spring:
  application:
    name: agroplace-api
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/agroplace_autenticacao?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Fortaleza}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
server:
  port: ${SERVER_PORT:8080}
